apiVersion: v1
kind: Service
metadata:
  name: zomatao-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: zomato
